Updated Survey Form UI
praveenscience/Creative-Simple-Landing-Pages pull request #95
Opened 2022-10-25 15:12 UTC by SSHSRN

Signed-off-by: SRIHARI S <sshsrn@gmail.com>

2022-10-25 15:14 UTC, SSHSRN commented
I have updated the UI of the survey form.

Before:
![image](https://user-images.githubusercontent.com/62781914/197812865-ff1a44d9-84ca-4cec-a685-c4c137adbe59.png)

After:
![image](https://user-images.githubusercontent.com/62781914/197812986-ad2d9c75-e6f2-4700-a3bb-0840d8df67b2.png)

2022-10-25 15:17 UTC, SSHSRN commented
@praveenscience Kindly check!

2022-10-28 01:05 UTC, praveenscience requested changes

2022-10-28 01:05 UTC, praveenscience commented on surveyform.html
> +        <center><h2 id="blue">About yourself</h2></center>
This tag is deprecated. Can we remove this and use CSS?

2022-10-28 01:05 UTC, praveenscience commented on surveyform.html
> +      <center><input class="submitBtn" type="submit" value="Submit" /></center>
This tag is deprecated. Can we remove this and use CSS?

2022-10-31 23:35 UTC, praveenscience commented
Any updates? It's the last few hours of Hacktoberfest? 😁

2023-02-08 02:26 UTC, closed without merging